export interface User {
    _id?: string; // Optional, as _id will be generated by MongoDB
    firstName: string;
    lastName: string;
    email: string;
    password: string;
    address?: string;
    role?: string;
  }
  
  // You can also create a class instead of an interface
  // export class User {
  //   constructor(
  //     public firstName: string,
  //     public lastName: string,
  //     public email: string,
  //     public password: string,
  //     public address?: string,
  //     public role?: string,
  //   ) {}
  // }
  